import '../models/unit_model.dart';

final List<Unit> initialMockUnits = [
  Unit(
    id: 'u101',
    buildingId: 'b1',
    number: 'A101',
    buildingName: 'عمارة القدس',
    status: 'مؤجرة',
    monthlyRent: 500,
    currentTenant: 'عبدالله حسين',
  ),
  Unit(
    id: 'u102',
    buildingId: 'b1',
    number: 'A102',
    buildingName: 'عمارة القدس',
    status: 'مؤجرة',
    monthlyRent: 500,
    currentTenant: 'محمد أحمد',
  ),
  Unit(
    id: 'u103',
    buildingId: 'b1',
    number: 'A103',
    buildingName: 'عمارة القدس',
    status: 'فارغة',
    monthlyRent: 480,
  ),
  Unit(
    id: 'u104',
    buildingId: 'b1',
    number: 'A104',
    buildingName: 'عمارة القدس',
    status: 'مؤجرة',
    monthlyRent: 520,
  ),
  Unit(
    id: 'u105',
    buildingId: 'b1',
    number: 'A105',
    buildingName: 'عمارة القدس',
    status: 'قيد التجهيز',
    monthlyRent: 500,
  ),
  Unit(
    id: 'u106',
    buildingId: 'b1',
    number: 'A106',
    buildingName: 'عمارة القدس',
    status: 'صيانة',
    monthlyRent: 500,
  ),
  Unit(
    id: 'u201',
    buildingId: 'b2',
    number: 'B101',
    buildingName: 'عمارة النور',
    status: 'مؤجرة',
    monthlyRent: 450,
    currentTenant: 'أحمد علي',
  ),
  Unit(
    id: 'u202',
    buildingId: 'b2',
    number: 'B102',
    buildingName: 'عمارة النور',
    status: 'فارغة',
    monthlyRent: 450,
  ),
  Unit(
    id: 'u301',
    buildingId: 'b3',
    number: 'B103',
    buildingName: 'عمارة الريان',
    status: 'مؤجرة',
    monthlyRent: 450,
    currentTenant: 'يوسف محمد',
  ),
  Unit(
    id: 'u302',
    buildingId: 'b3',
    number: 'B104',
    buildingName: 'عمارة الريان',
    status: 'مؤجرة',
    monthlyRent: 450,
  ),
  Unit(
    id: 'u303',
    buildingId: 'b3',
    number: 'B105',
    buildingName: 'عمارة الريان',
    status: 'فارغة',
    monthlyRent: 400,
  ),
  Unit(
    id: 'u304',
    buildingId: 'b3',
    number: 'B106',
    buildingName: 'عمارة الريان',
    status: 'مؤجرة',
    monthlyRent: 420,
  ),
];
